# CardSecure: Credit Card Risk Scoring & Approval System

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Data Understanding and Pre-processing

In [2]:
credit_data = pd.read_excel(
    r"C:\Users\8341s\Documents\ML Specialization\Model Development\CardSecure\data\credit_card_client_data.xls"
)

In [3]:
credit_data

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29996,29996,220000,1,3,1,39,0,0,0,0,0,0,188948,192815,208365,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29997,29997,150000,1,3,2,43,-1,-1,-1,-1,0,0,1683,1828,3502,8979,5190,0,1837,3526,8998,129,0,0,0
29998,29998,30000,1,2,2,37,4,3,2,-1,0,0,3565,3356,2758,20878,20582,19357,0,0,22000,4200,2000,3100,1
29999,29999,80000,1,3,1,41,1,-1,0,0,0,-1,-1645,78379,76304,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
30000,30000,50000,1,2,1,46,0,0,0,0,0,0,47929,48905,49764,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [4]:
# Make the first row the column names
credit_data.columns = credit_data.iloc[0]

# Remove the first row since it's now the header
credit_data = credit_data.iloc[1:].reset_index(drop=True)

# Check the result
credit_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [5]:
credit_data.rename(columns={"default payment next month" : "target"}, inplace=True)

In [6]:
credit_data.columns = credit_data.columns.str.lower()

In [7]:
credit_data.head()

,id,limit_bal,sex,education,marriage,age,pay_0,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.
X2: Gender (1 = male; 2 = female).
X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).
X4: Marital status (1 = married; 2 = single; 3 = others).
X5: Age (year).
X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as foll
ows: X6 = the repayment status in September, 2
005; X7 = the repayment status in August, 2005; .
 . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.
X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 0; .
 . .; X17 = amount of bill statement in April, 2005. 
X18-X23: Amount of previous payment (NT do
llar). X18 = amount paid in September,
 2005; X19 = amount paid in August, 2005;
 . . .;X23 = amount paid in April, 2005.

In [8]:
credit_data.isna().sum()

0
id           0
limit_bal    0
sex          0
education    0
marriage     0
age          0
pay_0        0
pay_2        0
pay_3        0
pay_4        0
pay_5        0
pay_6        0
bill_amt1    0
bill_amt2    0
bill_amt3    0
bill_amt4    0
bill_amt5    0
bill_amt6    0
pay_amt1     0
pay_amt2     0
pay_amt3     0
pay_amt4     0
pay_amt5     0
pay_amt6     0
target       0
dtype: int64

In [9]:
credit_data.duplicated().sum()

0

In [10]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         30000 non-null  object
 1   limit_bal  30000 non-null  object
 2   sex        30000 non-null  object
 3   education  30000 non-null  object
 4   marriage   30000 non-null  object
 5   age        30000 non-null  object
 6   pay_0      30000 non-null  object
 7   pay_2      30000 non-null  object
 8   pay_3      30000 non-null  object
 9   pay_4      30000 non-null  object
 10  pay_5      30000 non-null  object
 11  pay_6      30000 non-null  object
 12  bill_amt1  30000 non-null  object
 13  bill_amt2  30000 non-null  object
 14  bill_amt3  30000 non-null  object
 15  bill_amt4  30000 non-null  object
 16  bill_amt5  30000 non-null  object
 17  bill_amt6  30000 non-null  object
 18  pay_amt1   30000 non-null  object
 19  pay_amt2   30000 non-null  object
 20  pay_amt3   30000 non-null  object
 21  pay_amt4   30000 non-null  object
 22  pay_amt5   30000 non-null  object
 23  pay_amt6   30000 non-null  object
 24  target     30000 non-null  object
dtypes: object(25)
memory usage: 5.7+ MB

In [11]:
credit_data.head()

,id,limit_bal,sex,education,marriage,age,pay_0,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [12]:
credit_data['sex'].value_counts(dropna=False)

sex
2    18112
1    11888
Name: count, dtype: int64

In [13]:
credit_data['education'].value_counts(dropna=False)

education
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64

In [14]:
#Education categories 0, 5, and 6 are undocumented in the dataset.Pooling into category 4 ("Others") to reduce noise and improve interpretability.

In [15]:
credit_data['education'] = credit_data['education'].replace({0:4, 5:4,6:4})

C:\Users\8341s\AppData\Local\Temp\ipykernel_20692\1137130934.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  credit_data['education'] = credit_data['education'].replace({0:4, 5:4,6:4})

In [16]:
credit_data['education'].value_counts().sort_index()

education
1    10585
2    14030
3     4917
4      468
Name: count, dtype: int64

In [17]:
credit_data['marriage'].value_counts(dropna=False)

marriage
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

In [18]:
#pooling unknown value 0 into 3 as others
credit_data['marriage'] = credit_data['marriage'].replace({0:3})

C:\Users\8341s\AppData\Local\Temp\ipykernel_20692\975959495.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  credit_data['marriage'] = credit_data['marriage'].replace({0:3})

In [19]:
credit_data['marriage'].value_counts().sort_index()

marriage
1    13659
2    15964
3      377
Name: count, dtype: int64

In [20]:
credit_data['age'].unique()

array([24, 26, 34, 37, 57, 29, 23, 28, 35, 51, 41, 30, 49, 39, 40, 27, 47,
       33, 32, 54, 58, 22, 25, 31, 46, 42, 43, 45, 56, 44, 53, 38, 63, 36,
       52, 48, 55, 60, 50, 75, 61, 73, 59, 21, 67, 66, 62, 70, 72, 64, 65,
       71, 69, 68, 79, 74], dtype=object)

In [21]:
credit_data.head()

,id,limit_bal,sex,education,marriage,age,pay_0,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [22]:
credit_data = credit_data.rename(columns={'pay_0': 'pay_1'})

In [23]:
credit_data

,id,limit_bal,sex,education,marriage,age,pay_1,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000,1,3,1,39,0,0,0,0,0,0,188948,192815,208365,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,0,0,1683,1828,3502,8979,5190,0,1837,3526,8998,129,0,0,0
29997,29998,30000,1,2,2,37,4,3,2,-1,0,0,3565,3356,2758,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,29999,80000,1,3,1,41,1,-1,0,0,0,-1,-1645,78379,76304,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,30000,50000,1,2,1,46,0,0,0,0,0,0,47929,48905,49764,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [24]:
credit_data['pay_1'].value_counts().sort_index()

pay_1
-2     2759
-1     5686
0     14737
1      3688
2      2667
3       322
4        76
5        26
6        11
7         9
8        19
Name: count, dtype: int64

Note: The original dataset documentation does not define the values 0 and -2. For this analysis:

-2 is interpreted as no bill generated for that month.
 0  is interpreted as payment made on time (current account).

In [25]:
credit_data["limit_bal"].describe()

count     30000
unique       81
top       50000
freq       3365
Name: limit_bal, dtype: int64

In [26]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         30000 non-null  object
 1   limit_bal  30000 non-null  object
 2   sex        30000 non-null  object
 3   education  30000 non-null  int64
 4   marriage   30000 non-null  int64
 5   age        30000 non-null  object
 6   pay_1      30000 non-null  object
 7   pay_2      30000 non-null  object
 8   pay_3      30000 non-null  object
 9   pay_4      30000 non-null  object
 10  pay_5      30000 non-null  object
 11  pay_6      30000 non-null  object
 12  bill_amt1  30000 non-null  object
 13  bill_amt2  30000 non-null  object
 14  bill_amt3  30000 non-null  object
 15  bill_amt4  30000 non-null  object
 16  bill_amt5  30000 non-null  object
 17  bill_amt6  30000 non-null  object
 18  pay_amt1   30000 non-null  object
 19  pay_amt2   30000 non-null  object
 20  pay_amt3   30000 non-null  object
 21  pay_amt4   30000 non-null  object
 22  pay_amt5   30000 non-null  object
 23  pay_amt6   30000 non-null  object
 24  target     30000 non-null  object
dtypes: int64(2), object(23)
memory usage: 5.7+ MB

In [27]:
credit_data = credit_data.apply(pd.to_numeric)

In [28]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         30000 non-null  int64
 1   limit_bal  30000 non-null  int64
 2   sex        30000 non-null  int64
 3   education  30000 non-null  int64
 4   marriage   30000 non-null  int64
 5   age        30000 non-null  int64
 6   pay_1      30000 non-null  int64
 7   pay_2      30000 non-null  int64
 8   pay_3      30000 non-null  int64
 9   pay_4      30000 non-null  int64
 10  pay_5      30000 non-null  int64
 11  pay_6      30000 non-null  int64
 12  bill_amt1  30000 non-null  int64
 13  bill_amt2  30000 non-null  int64
 14  bill_amt3  30000 non-null  int64
 15  bill_amt4  30000 non-null  int64
 16  bill_amt5  30000 non-null  int64
 17  bill_amt6  30000 non-null  int64
 18  pay_amt1   30000 non-null  int64
 19  pay_amt2   30000 non-null  int64
 20  pay_amt3   30000 non-null  int64
 21  pay_amt4   30000 non-null  int64
 22  pay_amt5   30000 non-null  int64
 23  pay_amt6   30000 non-null  int64
 24  target     30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [29]:
credit_data["age"].describe()

count    30000.000000
mean        35.485500
std          9.217904
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: age, dtype: float64

In [30]:
credit_data["limit_bal"].describe()

count      30000.000000
mean      167484.322667
std       129747.661567
min        10000.000000
25%        50000.000000
50%       140000.000000
75%       240000.000000
max      1000000.000000
Name: limit_bal, dtype: float64

In [31]:
credit_data[
    ["bill_amt1","bill_amt2","bill_amt3", "bill_amt4","bill_amt5","bill_amt6"]
].describe()

,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6
count,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,30000.000000
mean,51223.330900,49179.075167,4.701315e+04,43262.948967,40311.400967,38871.760400
std,73635.860576,71173.768783,6.934939e+04,64332.856134,60797.155770,59554.107537
min,-165580.000000,-69777.000000,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000
25%,3558.750000,2984.750000,2.666250e+03,2326.750000,1763.000000,1256.000000
50%,22381.500000,21200.000000,2.008850e+04,19052.000000,18104.500000,17071.000000
75%,67091.000000,64006.250000,6.016475e+04,54506.000000,50190.500000,49198.250000
max,964511.000000,983931.000000,1.664089e+06,891586.000000,927171.000000,961664.000000

In [32]:
credit_data.head()

,id,limit_bal,sex,education,marriage,age,pay_1,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [35]:
credit_data.target.value_counts()

target
0    23364
1     6636
Name: count, dtype: int64

#

In [36]:
credit_data.groupby("sex")["target"].value_counts(normalize=True).mul(100).round(2)
#male = 1, female = 2 ==> males defaulting slightly more than females

sex  target
1    0         75.83
     1         24.17
2    0         79.22
     1         20.78
Name: proportion, dtype: float64

In [37]:
credit_data.groupby("education")["target"].value_counts(normalize=True).mul(100).round(2)
# (1 = graduate school; 2 = university; 3 = high school; 4 = others)
#high school graduates have the highest defeault rate

education  target
1          0         80.77
           1         19.23
2          0         76.27
           1         23.73
3          0         74.84
           1         25.16
4          0         92.95
           1          7.05
Name: proportion, dtype: float64

In [38]:
credit_data.groupby("marriage")["target"].value_counts(normalize=True).mul(100).round(2)
# (1 = married; 2 = single; 3 = others)
# singles default rate is less

marriage  target
1         0         76.53
          1         23.47
2         0         79.07
          1         20.93
3         0         76.39
          1         23.61
Name: proportion, dtype: float64

In [39]:
# creating age groups
bins = [20, 30, 40, 50, 60, credit_data["age"].max() + 1]
labels = ["20s", "30s", "40s", "50s", "60+"]

credit_data["age_group"] = pd.cut(
    credit_data["age"],
    bins=bins,
    labels=labels,
    right=False
)

In [40]:
credit_data["age_group"].value_counts()

age_group
30s    11238
20s     9618
40s     6464
50s     2341
60+      339
Name: count, dtype: int64

In [41]:
credit_data.groupby("age_group")["target"].value_counts(normalize=True).mul(100).round(2)
#highest default rate is seen in 60+ age group bit it has significantly lower counts
# lowest default rate seen in 30s age group

C:\Users\8341s\AppData\Local\Temp\ipykernel_20692\1613345935.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  credit_data.groupby("age_group")["target"].value_counts(normalize=True).mul(100).round(2)

age_group  target
20s        0         77.16
           1         22.84
30s        0         79.75
           1         20.25
40s        0         77.03
           1         22.97
50s        0         75.14
           1         24.86
60+        0         71.68
           1         28.32
Name: proportion, dtype: float64

In [42]:
credit_data.head()

,id,limit_bal,sex,education,marriage,age,pay_1,pay_2,pay_3,pay_4,pay_5,pay_6,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,target,age_group
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1,20s
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1,20s
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0,30s
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0,30s
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0,50s

In [43]:
credit_data["cumulative_bill"] = credit_data[
    [
        "bill_amt1",
        "bill_amt2",
        "bill_amt3",
        "bill_amt4",
        "bill_amt5",
        "bill_amt6"
    ]
].sum(axis=1)

In [44]:
credit_data.groupby("age_group")["cumulative_bill"]

C:\Users\8341s\AppData\Local\Temp\ipykernel_20692\3414995110.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  credit_data.groupby("age_group")["cumulative_bill"]

In [45]:
credit_data.to_csv(
    r"C:\Users\8341s\Documents\ML Specialization\Model Development\CardSecure\data\credit_data_clean.csv",
    index=False
)